rename 'core' to 'stores'

diff --git a/scripts/bash-functions b/scripts/bash-functions
--- a/scripts/bash-functions
+++ b/scripts/bash-functions
@@ -357,12 +357,12 @@ confirm-barman () {
     return 0
 }
 
-remove-core-container () {
+remove-stores-container () {
 	# If there is no such container, then nothing to do
     if container-exists $1; then
         echo -n $PROGNAME': Removing Container '$1' ... '
         docker stop --time 10 $1 2>&1 >/dev/null
-	    docker-compose $CORE_COMPOSE_ARGS rm -f -v $1 &> /dev/null
+	    docker-compose $STORES_COMPOSE_ARGS rm -f -v $1 &> /dev/null
         echo 'done'
     fi
 }
@@ -387,11 +387,11 @@ start-container () {
     return $?
 }
 
-start-core-container () {
+start-stores-container () {
     echo -n $PROGNAME': Starting '$1' ... '
 
     source ./.tcs-pg-ports
-    if ! docker-compose $CORE_COMPOSE_ARGS up -d $1 &> /dev/null; then
+    if ! docker-compose $STORES_COMPOSE_ARGS up -d $1 &> /dev/null; then
         return 1
     fi
 
@@ -406,7 +406,7 @@ start-active-pg-container () {
     if ! change-pgdata-owner postgres $1; then exit 1; fi
 
     # Now start the incoming Postgres container
-    if ! start-core-container $1; then error-exit 'Failed to Start Container '$1; fi
+    if ! start-stores-container $1; then error-exit 'Failed to Start Container '$1; fi
 
     sleep 5; # Allow for creation of new database
     
