Single PG

diff --git a/scripts/bash-functions b/scripts/bash-functions
--- a/scripts/bash-functions
+++ b/scripts/bash-functions
@@ -166,18 +166,18 @@ alter-archive-command () {
     for i in {1..10}
     do
         sleep 2
-        if ! docker exec -it $1 sh -c 'psql -c "ALTER SYSTEM SET archive_command TO true;" -U postgres; exit $?;'; then 
-            func-error $FUNCNAME $LINENO $1' Failed to Alter archive_command';
+        if ! docker exec -it pg1 sh -c 'psql -c "ALTER SYSTEM SET archive_command TO true;" -U postgres; exit $?;'; then 
+            func-error $FUNCNAME $LINENO 'pg1 Failed to Alter archive_command';
             continue
         fi
         sleep 3
-        if ! docker exec -it $1 sh -c 'psql -c "SELECT pg_reload_conf();" -U postgres; exit $?;'; then 
-            func-error $FUNCNAME $LINENO $1' Failed to Reload Postgres';
+        if ! docker exec -it pg1 sh -c 'psql -c "SELECT pg_reload_conf();" -U postgres; exit $?;'; then 
+            func-error $FUNCNAME $LINENO 'pg1 Failed to Reload Postgres';
             continue
         fi
         return 0
     done
-    func-error $FUNCNAME $LINENO $1' Unable to Alter archive_command';
+    func-error $FUNCNAME $LINENO 'pg1 Unable to Alter archive_command';
     return 1
 }
 
@@ -188,25 +188,25 @@ enable-barman-backups () {
 
     pg-state &> /dev/null
     
-    if ! barman-enable-streaming $1; then return 1; fi
+    if ! barman-enable-streaming pg1; then return 1; fi
 
     # archive_command set 'true'
-    if ! alter-archive-command $1; then return 1; fi
+    if ! alter-archive-command pg1; then return 1; fi
 
     # Any partly done streaming is useless - discard
-    if ! barman-clear-legacy-streaming $1; then return 1; fi
+    if ! barman-clear-legacy-streaming pg1; then return 1; fi
 
     # Ensure the Postgres replication slot exists
-    barman-create-slot $1;
+    barman-create-slot pg1;
 
     # Do a master reset on Barman
-    if ! barman-reset $1; then return 1; fi
+    if ! barman-reset pg1; then return 1; fi
 
     # Kick streaming to life
     if ! barman-cron; then return 1; fi
 
     # Now do a final sanity check
-    if ! barman-check $1; then return 1; fi
+    if ! barman-check pg1; then return 1; fi
 
     echo 'done'
     return 0
@@ -226,7 +226,7 @@ func-error () {
 
 barman-check () {
 	
-    if [ $# != 1 ]; then func-error $FUNCNAME $LINENO 'Incorrect parameter count'; return 1; fi
+    if [ $# != 0 ]; then func-error $FUNCNAME $LINENO 'Incorrect parameter count'; return 1; fi
 
     for i in {1..10}
     do
@@ -237,13 +237,15 @@ barman-check () {
     done
 
     # If barman configuration fails, report why
-    docker exec -it barman sh -c 'barman check '$1'; exit $?;'
+    docker exec -it barman sh -c 'barman check pg1; exit $?;'
     msg $1' Stream Replication Activation Failed';
     return 1
 }
 
 barman-create-slot () {
-	docker exec -it barman sh -c 'barman receive-wal --create-slot '$1'; exit $?;' &> /dev/null
+    if [ $# != 0 ]; then func-error $FUNCNAME $LINENO 'Incorrect parameter count'; return 1; fi
+
+	docker exec -it barman sh -c 'barman receive-wal --create-slot pg1; exit $?;' &> /dev/null
 }
 
 barman-cron () {
@@ -306,22 +308,6 @@ barman-clear-legacy-streaming () {
     fi
 }
 
-barman-enable-streaming () {
-    return 0
-    if ! docker exec -it barman sh -c 'cp /etc/barman.d/'$1'.conf_hold /etc/barman.d/'$1'.conf; exit $?;'; then
-        func-error $FUNCNAME $LINENO 'Attempt to enable '$1' streaming failed';
-        return 1
-    fi
-}
-
-barman-disable-streaming () {
-    return 0
-    if ! docker exec -it barman sh -c 'rm /etc/barman.d/'$1'.conf; exit $?;'; then
-        func-error $FUNCNAME $LINENO 'Attempt to disable '$1' streaming failed';
-        return 1
-    fi
-}
-
 barman-pitr () {
 
     echo -n $PROGNAME': Point-In-Time Recovery to '$1' ... '
@@ -355,7 +341,7 @@ barman-pitr () {
 }
 
 barman-reset () {
-	if ! docker exec -it barman sh -c 'barman receive-wal --reset '$1'; exit $?;' &> /dev/null; then
+	if ! docker exec -it barman sh -c 'barman receive-wal --reset pg1; exit $?;' &> /dev/null; then
         msg $1' Failed to Reset Stream Replication';      
     fi
 }
@@ -425,17 +411,17 @@ start-stores-container () {
 
 start-active-pg-container () {
 
-    source ./.tcs-pg-ports
+    if [ $# != 0 ]; then func-error $FUNCNAME $LINENO 'Incorrect parameter count'; fi
 
     # Ensure Postgres owns everything
-    if ! change-pgdata-owner postgres $1; then return 1; fi
+    if ! change-pgdata-owner postgres pg1; then return 1; fi
 
     # Now start the incoming Postgres container
-    if ! start-stores-container $1; then func-error 'Failed to Start Container '$1; fi
+    if ! start-stores-container pg1; then func-error 'Failed to Start Container pg1'; fi
 
     sleep 5; # Allow for creation of new database
     
-    if ! enable-barman-backups $1; then return 1; fi
+    if ! enable-barman-backups pg1; then return 1; fi
 
     return 0;
 }
diff --git a/scripts/stores b/scripts/stores
--- a/scripts/stores
+++ b/scripts/stores
@@ -10,72 +10,69 @@ cleanup () {
 }
 
 # ensure input params validity
-if [ "$#" != 1 ]; then error-exit "$USAGE"; fi
-
-case "$1" in
-	[-][v])
+if [ "$#" != 0 ] && [ $# != 1 ]; then error-exit "$USAGE"; fi
+if [ $# == 1 ]; then
+	if [ $1 == 'down' ]; then
+		docker-compose $STORES_COMPOSE_ARGS down;
+		exit 0
+	elif [ $1 == '-v' ]; then
 		echo 'TCS Version'$TCS_VERSION
 		exit 0
-		;;
-	[d][o][w][n])
-		docker-compose $STORES_COMPOSE_ARGS down
-		;;
-	[p][g][1] | [p][g][2])
-		# 5432 is the ACTIVE port, 5433 is STANDBY
-		set-pg-ports $1
-		source ./.tcs-pg-ports
+	else
+		error-exit "$USAGE"; 
+	fi
+fi
 
-		# Ensure we have the correct image and, if not, go get it
-		if [ -z ${TCS_VERSION+x} ]; then echo "TCS_VERSION undefined"; exit 1; fi
+# 5432 is the ACTIVE port, 5433 is STANDBY
+set-pg-ports $1
+source ./.tcs-pg-ports
 
-		# Ensure tcs-image is up-to-date
-		echo -n $PROGNAME': Ensure tcs-image is current ... '
-		if docker pull ccbcadmin/tcs-image$TCS_VERSION 2>&1 >/dev/null; then 
-			echo 'done'; 
-		else
-			error-exit 'failed';
-		fi
+# Ensure we have the correct image and, if not, go get it
+if [ -z ${TCS_VERSION+x} ]; then echo "TCS_VERSION undefined"; exit 1; fi
 
-		# Clean things up if things go awry
-		trap cleanup EXIT
+# Ensure tcs-image is up-to-date
+echo -n $PROGNAME': Ensure tcs-image is current ... '
+if docker pull ccbcadmin/tcs-image$TCS_VERSION 2>&1 >/dev/null; then 
+	echo 'done'; 
+else
+	error-exit 'failed';
+fi
 
-		# Barman must own its home area
-        if ! docker-compose $STORES_COMPOSE_ARGS run --rm --entrypoint bash barman -c \
-			'chown -R barman.barman /var/lib/barman &>/dev/null; exit $?;'; then 
-			error-exit 'Failed to config barman ownership';
-		fi
+# Clean things up if things go awry
+trap cleanup EXIT
 
-		if ! container-exists barman; then
-			if ! start-stores-container barman; then
-				error-exit 'Failed to Start Container barman'; 
-			fi
-		fi
+# Barman must own its home area
+if ! docker-compose $STORES_COMPOSE_ARGS run --rm --entrypoint bash barman -c \
+	'chown -R barman.barman /var/lib/barman &>/dev/null; exit $?;'; then 
+	error-exit 'Failed to config barman ownership';
+fi
 
-		# Start the selected Postgres container
-		if ! container-exists $1; then
-			if ! start-active-pg-container $1; then 
-				error-exit 'Failed to Start Container '$1;
-			fi
-		fi
+if ! container-exists barman; then
+	if ! start-stores-container barman; then
+		error-exit 'Failed to Start Container barman'; 
+	fi
+fi
 
-		if ! container-exists rabbitmq; then
-			if ! start-stores-container rabbitmq; then
-				error-exit 'Failed to Start Container rabbitmq';
-			fi
-		fi
+# Start the selected Postgres container
+if ! container-exists $1; then
+	if ! start-active-pg-container pg1; then 
+		error-exit 'Failed to Start Container '$1;
+	fi
+fi
 
-		if ! container-exists jenkins; then
-			if ! start-stores-container jenkins; then
-				error-exit 'Failed to Start Container jenkins';
-			fi
-		fi
+if ! container-exists rabbitmq; then
+	if ! start-stores-container rabbitmq; then
+		error-exit 'Failed to Start Container rabbitmq';
+	fi
+fi
 
-		# No need for a cleanup
-		trap '' EXIT;
+if ! container-exists jenkins; then
+	if ! start-stores-container jenkins; then
+		error-exit 'Failed to Start Container jenkins';
+	fi
+fi
 
-		exit 0
-		;;
-	*) error-exit "$USAGE";
-		;;
-esac
+# No need for a cleanup
+trap '' EXIT;
 
+exit 0
