Single PG

diff --git a/scripts/bash-functions b/scripts/bash-functions
--- a/scripts/bash-functions
+++ b/scripts/bash-functions
@@ -392,14 +392,15 @@ start-stores-container () {
 
 start-barman () {
 
-    # Barman must own its home area
-    if ! docker-compose $STORES_COMPOSE_ARGS run --rm --entrypoint bash barman -c \
-        'chown -R barman.barman /var/lib/barman &>/dev/null; exit $?;'; then 
-        func-error $FUNCNAME $LINENO 'Failed to config barman ownership';
-        return 1
-    fi
-
     if ! container-exists barman; then
+
+        # Barman must own its home area
+        if ! docker-compose $STORES_COMPOSE_ARGS run --rm --entrypoint bash barman -c \
+            'chown -R barman.barman /var/lib/barman &>/dev/null; exit $?;'; then 
+            func-error $FUNCNAME $LINENO 'Failed to config barman ownership';
+            return 1
+        fi
+
         if ! start-stores-container barman; then
             func-error $FUNCNAME $LINE 'Failed to Start barman';
         fi
