Single PG

diff --git a/scripts/pg-rollback-recovery b/scripts/pg-rollback-recovery
--- a/scripts/pg-rollback-recovery
+++ b/scripts/pg-rollback-recovery
@@ -4,7 +4,6 @@ PROGNAME=$(basename $0)
 USAGE='Usage: '$PROGNAME' backup_id [target_time]'
 
 source ./scripts/bash-functions
-source ./.tcs-pg-ports
 
 echo -n "Executing this command will result in data loss.  Proceed? [yes or no]: "
 read yno
@@ -24,18 +23,15 @@ if [ "$#" != 1 ] && [ "$#" != 2 ] ; then error-exit "$USAGE"; fi
 
 validate-pg-selection $1 "$USAGE"
 
-validate-backup_id $1 $2
-
-# Get the statuses of the Postgres containers
-pg-state &> /dev/null
+validate-backup_id $1
 
 # Shutdown the active Postgres container
 if ! remove-stores-container pg1; exit 1; fi
 
 # Do the recovery
 case "$#" in
-	2)	if ! barman-recover pg1 $@; then error-exit 'Recovery Failure'; fi ;;
-	3)  if ! barman-pitr pg1 $@; then error-exit 'Recover Failure'; fi ;;
+	1)	if ! barman-recover pg1 $1; then error-exit 'Recovery Failure'; fi ;;
+	2)  if ! barman-pitr pg1 $1 $2; then error-exit 'Recover Failure'; fi ;;
 	*)  error-exit 'Assertion Error @ '$LINENO ;;
 esac
 
