Single PG

diff --git a/scripts/pg-standby-recovery b/scripts/pg-standby-recovery
--- a/scripts/pg-standby-recovery
+++ b/scripts/pg-standby-recovery
@@ -17,14 +17,18 @@ remove-stores-container pg2
 
 # Do the recovery
 case "$#" in
-	1)	echo "Here"; if ! barman-recover pg2 $@; then error-exit 'Recovery Failure'; fi ;;
+	1)	echo "Here 1"; if ! barman-recover pg2 $@; then error-exit 'Recovery Failure'; fi ;;
 	2)  if ! barman-pitr pg2 $@; then error-exit 'Recovery Failure'; fi ;;
 	*)  error-exit 'Assertion Error @ '$LINENO ;;
 esac
 msg 'Recovery Successful'
 
+echo "Here 2"
+
 # Ensure Postgres owns everything
 if ! change-pgdata-owner postgres pg2; then exit 1; fi
+
+echo "Here 3"
 
 # Finally bring up the STANDBY container to listen on port 5433
 if ! start-stores-container pg2; then exit 1; fi
